### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by OnceUponALoop** [kangtastic/peapod#1]
Not an issue - please close.

Just wanted to let you know that this is one hell of a project. I'm not even using it (eap_proxy on ER4) but the amount of work you put into the documentation, code comments, and readme is impressive and I figured you wouldn't mind hearing that 😃

**Comment by kangtastic** [comment]
I suppose I did put a lot of work into this project, but I don't mind. My fork of eap_proxy for non-Vyatta/VyOS/EdgeOS distributions was serving my needs fine too. And then I thought, 'I've come this far and learned this much by derping around. Why not derp... some more?' :smirk:

But thanks! I'm still not a very good programmer and I've always thought of my "open source involvement" as primarily for myself, so it's always really cool when someone's like, "Hey, I like this thing you did".

(Sorry about the late reply; I missed the notification somehow.)
